name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Tommy second test
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: ./action-a
      env:
        MY_NAME: "Mona"

workflow "Deploy Master" {
  on = "push"
  resolves = ["cow"]
}

action "cow" {
  uses = "mscoutermarsh/cowsays-action@master"
  args = "Ship it!!!!!"
}
